[package]
name = "funlang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
funlang_derive = { path = "../funlang_derive" }
